[package]
name = "nnue-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "validate"
path = "src/bin/validate.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
